name: extractor
version: 1.0.0
description: scraper for dramacool
homepage: https://github.com/Toasty360/DramaExtractor
repository:
  type: git
  url: git://github.com/Toasty360/DramaExtractor.git

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio:
  html:
  toast:
  hive:
  hive_flutter:
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  hive_generator:
  build_runner:
